# Generated by Django 2.1.1 on 2018-10-03 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180927_1846'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.CharField(max_length=255, null=True, verbose_name='Pergunta')),
                ('quest1', models.CharField(max_length=255, verbose_name='Questao01')),
                ('quest2', models.CharField(max_length=255, verbose_name='Questao02')),
                ('quest3', models.CharField(max_length=255, verbose_name='Questao03')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='nome',
            field=models.CharField(max_length=100, null=True, verbose_name='Nome'),
        ),
    ]
